# permissions for end users to edit performers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: performer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: show
    app.kubernetes.io/part-of: show
    app.kubernetes.io/managed-by: kustomize
  name: performer-editor-role
rules:
- apiGroups:
  - demo.mctest.io
  resources:
  - performers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.mctest.io
  resources:
  - performers/status
  verbs:
  - get
