# permissions for end users to edit shows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: show-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: show
    app.kubernetes.io/part-of: show
    app.kubernetes.io/managed-by: kustomize
  name: show-editor-role
rules:
- apiGroups:
  - demo.mctest.io
  resources:
  - shows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.mctest.io
  resources:
  - shows/status
  verbs:
  - get
